version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    
    # Even though we use yarn, according to the documentation, value should be 'npm': 
    # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-
  - package-ecosystem: "npm" 
    directories:
      - "/campaign-launcher/client"
      - "/campaign-launcher/server"
      - "/recording-oracle"
      - "/reputation-oracle"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    # By default dependabot doesn't respect semver ranges in package.json,
    # so we switch to this versioning strategy to have such deps highlighted
    # instead of increasing them all
    versioning-strategy: increase-if-necessary
    target-branch: "develop"
    ignore:
        # Not compatible w/ jest: https://fakerjs.dev/guide/upgrading#incompatibility-with-jest
      - dependency-name: "@faker-js/faker"
        versions: [">=10.0.0"]
        # Not compatible w/ typescript-eslint atm: https://github.com/typescript-eslint/typescript-eslint/issues/11952
      - dependency-name: "eslint"
        versions: [">=10.0.0"]
      - dependency-name: "@eslint/js"
        versions: [">=10.0.0"]
    # Grouping minor and patch updates to 1 PR to reduce the noise:
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates#example-3-individual-pull-requests-for-major-updates-and-grouped-for-minorpatch-updates
    groups:
      minor-patch-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 5 # Reasonable number to start with