---
- name: Reload AppArmor
  ansible.builtin.systemd:
    name: apparmor
    state: reloaded
  become: true

- name: Restart QGS
  ansible.builtin.systemd:
    name: qgsd
    state: restarted
  become: true

- name: Restart PCCS
  ansible.builtin.systemd:
    name: pccs
    state: restarted
  become: true
